server:
  port: 8020
spring:
  application:
    name: Zuul
zuul:
  routes:
    consumer: /user/**

eureka:
  client:
    service-url:
      defaultZone: ${eureka.client.service-url.defaultZone}




#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:7001/eureka/
#
#zuul:
#  routes:
#    consumer: /user/**
#  prefix: /zuul
#  ignored-services: "*"  #让其它链接失效